
[project]
name = "webhook-gateway"
version = "0.1.0"
description = "A robust webhook gateway to ingest, validate, and dispatch webhooks from various sources."
authors = [{ name = "Your Name", email = "you@example.com" }]

requires-python = ">=3.10"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "pydantic",
    "mysqlclient", # Driver for MySQL
    "aiomysql", # Async MySQL driver
    "pymysql", # Required by aiomysql
    "alembic", # For database migrations
    "python-multipart", # For handling form data
    "lxml", # For handling XML
    "pydantic-settings", # For managing settings
    "httpx",
    "aiosqlite>=0.21.0",
    "requests>=2.32.4",
    "chardet>=5.2.0",
    "sqlalchemy[asyncio]>=2.0.41",
    "prometheus_client>=0.20.0",
    "taskiq>=0.11.18",
    "taskiq-aio-pika>=0.4.3",
    "ulid-rs-py>=0.3.1",
]


[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.ruff]
line-length = 88

[tool.black]
line-length = 88

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ipython>=8.37.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.0",
]
